steps:

 # Step1: Clone source code
 - name: 'gcr.io/cloud-builders/git'
   args: ['clone', 'https://github.com/teatm/cloud-build-sync']

 # Step2: Build Docker image

 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/calendar-app', '.']

 # Step3: Push built image to Artifact Registry

 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/calendar-app']

 # Step4: Install dependencies and run tests

 - name: 'gcr.io/cloud-builders/npm'
   args: ['install']

 - name: 'gcr.io/cloud-builders/npm'
   args: ['run', 'test']

 # Step5: Apply GKE deployment

 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['container', 'clusters', 'get-credentials', 'autopilot-cluster-calendar', '--zone', 'us-central1', '--project', '$PROJECT_ID']

 # Step6: Apply deployment and service with kubectl

 - name: 'gcr.io/cloud-builders/kubectl'
   args: ['apply', '-f', 'deployment.yaml']
   env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
     - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-calendar'

 - name: 'gcr.io/cloud-builders/kubectl'
   args: ['apply', '-f', 'service.yaml']
   env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
     - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-calendar'

images:
 - 'gcr.io/$PROJECT_ID/calendar-app'
