apiVersion: apps/v1

kind: Deployment
metadata:
 name: calendar-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: calendar
 template:
   metadata:
     labels:
       app: calendar
   spec:
     containers:
     - name: calendar-container
       image: gcr.io/${project_id}/calendar-app:latest
       ports:
       - containerPort: 80